name: graphcpp
channels:
  - pytorch
  - pyg
  - nvidia
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - pytorch==1.13.1
  - torchvision==0.14.1
  - torchaudio==0.13.1
  - pytorch-cuda=11.7
  - pyg=2.3.0
  - rdkit=2022.09.5
  - tqdm=4.65.0
  - deepchem=2.7.1
  - lightning=2.0.1.post0
  - arm-mango=1.3.1
  - scikit-learn=1.2.2
  - matplotlib
  - seaborn
  - scipy
  - pip
  - pip:
      - --find-links https://data.pyg.org/whl/torch-2.0.0+cu117.html
      - torch-scatter==2.1.1
      - torch-sparse==0.6.17
  - pip:
      - torchaudio==0.13.1
      - torchvision==0.14.1
      - streamlit==1.21.0